-- drop tables in the opposite order of their creation
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS SHOPPING_BAG_ROW;
DROP TABLE IF EXISTS SHOPPING_BAG;
DROP TABLE IF EXISTS USER_ADRESSES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CATEGORY_GAME;
DROP TABLE IF EXISTS PHYSICAL_GAME;
DROP TABLE IF EXISTS GAME;
DROP TABLE IF EXISTS CONSOLE;
DROP TABLE IF EXISTS CATEGORY;
