-- drop tables in the opposite order of their creation
DELETE FROM USER_ROLES;
DELETE FROM ROLES;
DELETE FROM ORDERS;
DELETE FROM SHOPPING_BAG_ROW;
DELETE FROM SHOPPING_BAG;
DELETE FROM USER_ADRESSES;
DELETE FROM USERS;
DELETE FROM ADDRESS;
DELETE FROM CATEGORY_GAME;
DELETE FROM PHYSICAL_GAME;
DELETE FROM GAME;
DELETE FROM CONSOLE;
DELETE FROM CATEGORY;
